# Generated by Django 2.1.15 on 2020-10-18 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('dataEntrega', models.DateField(verbose_name='Data de entrega')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('INICIADO', 'Iniciado'), ('FINALIZADO', 'Finalizado')], default='PENDENTE', max_length=10)),
                ('isAvaliativo', models.BooleanField(verbose_name='É avaliativo?')),
                ('descricao', models.CharField(max_length=180, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('dataInicio', models.DateField(verbose_name='Data de ínicio')),
                ('dataFinal', models.DateField(verbose_name='Data final')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('nomeProfessor', models.CharField(max_length=150, verbose_name='Nome do Professor(a)')),
                ('emailProfessor', models.CharField(max_length=150, verbose_name='E-mail do Professor(a)')),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='bloco_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Bloco', verbose_name='Bloco'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Disciplina', verbose_name='Disciplina'),
        ),
    ]
