# Generated by Django 2.1.15 on 2020-10-06 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('dataEntrega', models.DateField(verbose_name='Data de entrega')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Iniciado', 'Iniciado'), ('Finalizado', 'Finalizado')], default='Selecione', max_length=1)),
                ('isAvaliativo', models.BooleanField()),
                ('descricao', models.CharField(max_length=180, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('dataInicio', models.DateField(verbose_name='Data de ínicio')),
                ('dataFinal', models.DateField(verbose_name='Data final')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('nomeProfessor', models.CharField(max_length=150, verbose_name='Nome do Professor(a)')),
                ('emailProfessor', models.CharField(max_length=150, verbose_name='E-mail do Professor(a)')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=150)),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='bloco',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Usuario'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Disciplina'),
        ),
    ]
